spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(/17MP9wKdeasPLIDsq4VakVuBEJ0lfVVkZKz/xq3ZUtk7bBWWC3sJuLAn8RqbP/ekD1BX/RBtdYKlx0yKIPfucZ0WRB59Vn8UmIqctKmWf7oZNJGaDS3Mg==)
    username: ENC(/mDZURmxFQzcZepa5RkYFw==)
    password: thwjddldi210.

logging:
  level:
    com.example.insuranceSystem: DEBUG
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR