spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(6lV+X47HLJVs7fT5OojiVPgnO0czgSb7cEa2/cSN3uCSHJG06qhPgKdLnBcXYnh4iQXXLLAYutSfZo9oBHBUsFx1MSWGBnHPgy0qmseSXt9EttCROlXYtw==)
    username: ENC(rtiNzhHRQHuP0jsMgiuWLA==)
    password: ENC(xj1VHbTh5chlk0BTFHgeEQ4xfqekcwPR)

logging:
  level:
    com.example.insuranceSystem: DEBUG
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

sms:
    service-id: ENC(eIDGQ5SX974DUfpRyPjb8IbWnvXhRs82N7QiAeT2VTMMP7iZh+pNaJjvp3THdakk)
    access-key: ENC(XUVvYQi6Uhdopa8ayCQqT24C5caYOy9GoxZ0Uj+uZaU=)
    secret-key: ENC(yNhfFOr3zm4I0e3g099z+gXpIUneTzH3To0VWtF4qSkecZ0cSWsrsulXoT221miblaKb79fkGE8=)
    phone-num: ENC(TJgO34Ogaae6e6xS+Hyql9QubOf+J7/R)
